server:
  context-path: /boot
  port: 8080

spring:
  thymeleaf:
    mode: LEGACYHTML5
  config:
    location: config/dev,config/test,config/prod
#  profiles:
#    active: config/${env}
#  mvc:
#    view:
#      prefix: /WEB-INF/view/
#      suffix: .jsp



#开发
app:
  datasource:
      driver: com.mysql.jdbc.Driver
      type: mysql
      url: jdbc:mysql://localhost:3306/web_app?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root

payment:
  datasource:
      driver: com.mysql.jdbc.Driver
      type: mysql
      url: jdbc:mysql://localhost:3306/medcfc_pay?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: root
